### PR TITLE
Added ability to get an array of the 4 quaternion values.

### PR DESCRIPTION
**Pull request by SimLeek**
Tested this with an Arduino nano and 9250 and was able to see the quaternions printed as I rotated the device.

### CODE REVIEW

**Comment by aster94** [comment]
Hello,

please add the fuction to https://github.com/aster94/SensorFusion/blob/master/keywords.txt and update the version number to 1.0.3 here: https://github.com/aster94/SensorFusion/blob/master/library.properties

This way your library manager would update the library automatically

**Comment by SimLeek** [comment]
Huh. Neat.

Added.

**Comment by aster94** [comment]
merged, thanks for the PR @SimLeek 😊

**Comment by SimLeek** [comment]
Yw! 🙂

**Pull request merged**
